package com.sidiabed.hotelservice.Enum;

public enum HotelJob{
    RECEPTIONIST, CONCIERGE, HOUSEKEEPER, ROOM_SERVICE_ATTENDANT, CHEF, KITCHEN_STAFF, BARTENDER, WAITER_WAITRESS, SECURITY_GUARD, VALET
}
